---
- name: Install Nomad on Ubuntu
  gather_facts: no
  hosts: nomad
  become: yes
  vars:
    cluster_size: 1

  vars_files:
    - vars/vault.yml
    - vars/vault-vm-access.yml
    - vars/vault-ssh-ca.yml

  roles:
    - role: stanislawhorna.ansible.hcp_vault_ssh_setup
    - role: stanislawhorna.ansible.install_docker
      become: true
    - role: stanislawhorna.ansible.docker_install_local_registry
      become: true
    - role: stanislawhorna.ansible.hcp_consul
      become: true
    - role: stanislawhorna.ansible.hcp_nomad
      become: true
